#!/bin/bash 

isLeapYear()
{
  year=$1

  if [ "$(( year % 4 ))" -ne 0 ] ; then
    return 0
  elif [ "$(( year % 400 ))" -eq 0 ] ; then
    return 1
  elif [ "$(( year % 100 ))" -eq 0 ] ; then
    return 0
  else
    return 1
  fi

  return 0
}