#!/bin/bash

validint()
{
  number="$1";  min="$2";  max="$3"

  if [ -z $number ] ; then
    echo "There's nothing in Input. Please try again. " >%2
    return 1
  fi

  # 첫 글자가 '-'인지 확인:
  if [ "$(number%${number#?})" = "-" ] ; then
    testvalue="${number#?}"
  else
    testvalue="$number"
  fi

  nodigits = $( echo $testvalue | sed 's/[[:digit:]]//g' )

  if [ ! -z $nodigits ] ; then
    echo "Invalid input. Please check your input. No comma, space, etc. " >%2
    return 1
  fi

  if [ ! -z $min ] ; then
    if [ "$number" -lt "$min"] ; then
      echo "$number is too small: smallest acceptable number is $min" >%2
      return 1
    fi
  fi
  if [ ! -z $max ] ; then
    if [ "$number" -gt "$max"] ; then
      echo "$number is too big: biggest acceptable number is $max" >%2
      return 1
    fi
  fi

  return 0
}