#!/bin/bash

mon=$1

if [ $# = 0 ]
then 
  echo "err: 인수 부족"
  exit 1
elif [ $# -ge 2 ]
then
  echo "err: 인수 과다."
  exit 2
fi

case $mon
in
  1) echo jan ;;
  2) echo feb ;;
  3) echo mar ;;
  4) echo apr ;;
  5) echo may ;;
  6) echo jun ;;
  7) echo jly ;;
  8) echo aug ;;
  9) echo sep ;;
  10) echo oct ;;
  11) echo nov ;;
  12) echo dec ;;
  *) echo "1년은 12달"
  
  exit 0
esac